CREATE TABLE noteful_notes (
    note_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    content TEXT NOT NULL,
    folder_id INTEGER
        REFERENCES noteful_folders(folder_id) ON DELETE CASCADE NOT NULL,
    modified TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE noteful_folders
    ADD COLUMN
        note_id INTEGER REFERENCES noteful_notes(note_id)
        ON DELETE SET NULL;